# Generated by Django 3.2.9 on 2022-10-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_files', '0002_auto_20221011_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_to', models.ImageField(blank=True, upload_to='blog_photos')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Upload_files.post')),
            ],
        ),
    ]
