# Generated by Django 3.2.9 on 2022-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_files', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_to',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
