# Generated by Django 3.2.9 on 2022-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_files', '0004_alter_image_upload_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post_id',
            new_name='post',
        ),
    ]
