# Generated by Django 3.2.9 on 2022-10-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_files', '0005_rename_post_id_image_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
