# Generated by Django 3.2.16 on 2022-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_files', '0006_alter_post_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_to',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
