# Generated by Django 3.2.16 on 2022-11-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_files', '0007_alter_image_upload_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='upload_to',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
